///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace tesst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the tesstRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("4629eab3-732b-4bbc-b5d3-519e07c70db5")]
    public partial class tesstRepository : RepoGenBaseFolder
    {
        static tesstRepository instance = new tesstRepository();

        /// <summary>
        /// Gets the singleton class instance representing the tesstRepository element repository.
        /// </summary>
        [RepositoryFolder("4629eab3-732b-4bbc-b5d3-519e07c70db5")]
        public static tesstRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public tesstRepository() 
            : base("tesstRepository", "/", null, 0, false, "4629eab3-732b-4bbc-b5d3-519e07c70db5", ".\\RepositoryImages\\tesstRepository4629eab3.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4629eab3-732b-4bbc-b5d3-519e07c70db5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class tesstRepositoryFolders
    {
    }
#pragma warning restore 0436
}